name: CI/CD pipeline

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'pnpm'

      - run: pnpm i --frozen-lockfile

      - run: pnpm format
      - run: pnpm lint
      - run: pnpm exec tsc --noEmit
      - run: pnpm build

  changes:
    runs-on: ubuntu-latest
    outputs:
      website: ${{ steps.filter.outputs.website }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            website:
              - '!**.md'

  cd:
    runs-on: ubuntu-latest
    needs: [ci, changes]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.website == 'true' }}
    strategy:
      matrix:
        variant: [dev, prod]
    environment: ${{ matrix.variant }}
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'pnpm'

      - name: Build
        env:
          VITE_SITE_VARIANT: ${{ matrix.variant }}
        run: |
          pnpm i
          pnpm build

      - name: Copy build via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: 'dist/*'
          target: ${{ secrets.CD_TARGET }}
          strip_components: 1
